In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,MinMaxScaler
from sklearn.svm import SVR #FOR REGRESSION
from sklearn.metrics import recall_score,precision_score,accuracy_score,r2_score,f1_score,mean_absolute_error,root_mean_squared_error,mean_squared_error

In [2]:
df=pd.read_csv(r'C:\Users\amank\Downloads\Learning_day_1\cardekho.csv')
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0

In [3]:
df.isnull().sum()

name                    0
year                    0
selling_price           0
km_driven               0
fuel                    0
seller_type             0
transmission            0
owner                   0
mileage(km/ltr/kg)    221
engine                221
max_power             215
seats                 221
dtype: int64

In [4]:
df.rename(columns={'mileage(km/ltr/kg)':'mileage'},inplace=True)

In [5]:
df.drop_duplicates()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8121,Maruti Wagon R VXI BS IV with ABS,2013,260000,50000,Petrol,Individual,Manual,Second Owner,18.90,998.0,67.1,5.0
8122,Hyundai i20 Magna 1.4 CRDi,2014,475000,80000,Diesel,Individual,Manual,Second Owner,22.54,1396.0,88.73,5.0
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.50,1197.0,82.85,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.80,1493.0,110,5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.30,1248.0,73.9,5.0

In [6]:
df.drop(columns=['max_power','name'],inplace=True)

In [7]:
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,seats
0,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,5.0
1,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,5.0
2,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,5.0
3,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,5.0
4,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,5.0

In [10]:
label=LabelEncoder()

In [11]:
df['encoded_fuel']=label.fit_transform(df['fuel'])
df['encoded_seller_type']=label.fit_transform(df['seller_type'])
df['encoded_transmission']=label.fit_transform(df['transmission'])
df['encoded_owner']=label.fit_transform(df['owner'])

In [12]:
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,seats,encoded_fuel,encoded_seller_type,encoded_transmission,encoded_owner
0,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,5.0,1,1,1,0
1,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,5.0,1,1,1,2
2,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,5.0,3,1,1,4
3,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,5.0,1,1,1,0
4,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,5.0,3,1,1,0

In [13]:
df.drop(columns=['fuel','seller_type','transmission','owner'],inplace=True)

In [14]:
df.head()

,year,selling_price,km_driven,mileage,engine,seats,encoded_fuel,encoded_seller_type,encoded_transmission,encoded_owner
0,2014,450000,145500,23.40,1248.0,5.0,1,1,1,0
1,2014,370000,120000,21.14,1498.0,5.0,1,1,1,2
2,2006,158000,140000,17.70,1497.0,5.0,3,1,1,4
3,2010,225000,127000,23.00,1396.0,5.0,1,1,1,0
4,2007,130000,120000,16.10,1298.0,5.0,3,1,1,0

In [15]:
x=df[['year','selling_price','km_driven','mileage','engine','seats','encoded_fuel','encoded_seller_type','encoded_transmission','encoded_owner']]
y=df['selling_price']

In [ ]:
x=x.fillna(x.mean())

# YOU CAN USE THIS TOO  (x or y bouth filling null values nah values filling)

# y=y.fillna(y.median())
# y=y.fillna(y.mode()[0])

In [ ]:
df.head()

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [18]:
model=SVR(kernel='linear',C=0.5)

In [ ]:
model.fit(x_train,y_train)

In [ ]:
y_pred=model.predict(x_test)
r2_score(y_test,y_pred)

mean_squared_error(y_test,y_pred)
root_mean_squared_error(y_test,y_pred)
mean_absolute_error(y_test,y_pred)